### Get all boxes
GET http://localhost:4004/odata/v2/api/Stampboxes
Authorization: Basic Kevin pass

### Get count of boxes
GET http://localhost:4004/odata/v2/api/Stampboxes/$count
Authorization: Basic Kevin pass

### Get all stampings done by Kevin
GET http://localhost:4004/odata/v2/api/Stampings
Authorization: Basic Kevin pass

### Post new Stamp for Kevin
POST http://localhost:4004/odata/v2/api/Stampings
Accept: application/json
content-type: application/json
Authorization: Basic Kevin pass

{
    "stamp": { "ID": "38bdea78-045d-420d-b589-aacb19447a7e"}
}

### Get all stampings done by Alice
GET http://localhost:4004/odata/v2/api/Stampings
Authorization: Basic Alice pass

### Post new Stamp for Alice
POST http://localhost:4004/odata/v2/api/Stampings
Accept: application/json
content-type: application/json
Authorization: Basic Alice pass

{
    "stamp": { "ID": "38bdea78-045d-420d-b589-aacb19447a7e"}
}

### Add a Stamp box
POST http://localhost:4004/odata/v2/api/Stampboxes
Accept: application/json
content-type: application/json
Authorization: Basic Kevin pass

{
"validFrom": "1970-01-01T00:00:01.0+00:00",
"validTo": "2037-12-31T23:00:01.000Z",
"longitude": "11.033540000",
"latitude": "55.58708",
"name": "Stelle X",
"description": "Beschreibung X",
"number": "Sonder XX",
"isKidFriendly": true,
"isElderlyFriendly": true,
"isStrollerFriendly": true,
"hasToilet": true,
"hasFood": true
}

### Get count of parking spaces
GET http://localhost:4004/odata/v2/api/ParkingSpots/$count
Authorization: Basic Kevin pass

### Get inital Neighbors
GET http://localhost:4004/odata/v2/api/NeighborsStampStamp
Authorization: Basic Kevin pass

### Start calculate for travelTimes
GET http://localhost:4004/odata/v2/api/calculateTravelTimesNNearestNeighbors?n=5
Authorization: Basic Kevin pass

### Get calculatd travelTimes
GET http://localhost:4004/odata/v2/api/TravelTimes
Authorization: Basic Kevin pass

### Get Tree for location
GET http://localhost:4004/odata/v2/api/tree
Authorization: Basic Kevin pass